---
# Network role tasks

- name: Install network packages
  apt:
    name:
      - bridge-utils
      - vlan
      - ifenslave
      - ethtool
      - iproute2
      - iputils-ping
      - tcpdump
      - nftables
    state: present

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Configure network bridges
  template:
    src: netplan-bridges.yml.j2
    dest: /etc/netplan/60-bridges.yaml
  notify: apply netplan

- name: Configure network interfaces
  template:
    src: netplan-interfaces.yml.j2
    dest: /etc/netplan/50-interfaces.yaml
  notify: apply netplan

- name: Configure nftables
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  notify: reload nftables

- name: Enable and start nftables
  systemd:
    name: nftables
    enabled: yes
    state: started

- name: Configure network tuning
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { key: "net.core.somaxconn", value: "65535" }
    - { key: "net.core.netdev_max_backlog", value: "4096" }
    - { key: "net.ipv4.tcp_max_syn_backlog", value: "4096" }
    - { key: "net.ipv4.tcp_syncookies", value: "1" }
    - { key: "net.ipv4.tcp_fin_timeout", value: "15" }
    - { key: "net.ipv4.tcp_keepalive_time", value: "300" }
    - { key: "net.ipv4.tcp_keepalive_probes", value: "5" }
    - { key: "net.ipv4.tcp_keepalive_intvl", value: "15" }
    - { key: "net.ipv4.tcp_tw_reuse", value: "1" }
    - { key: "net.ipv4.tcp_max_tw_buckets", value: "262144" }
    - { key: "net.ipv4.tcp_fastopen", value: "3" }
    - { key: "net.ipv4.tcp_slow_start_after_idle", value: "0" }

- name: Configure network QoS
  template:
    src: tc-qos.sh.j2
    dest: /usr/local/bin/tc-qos.sh
    mode: '0755'

- name: Configure QoS service
  template:
    src: tc-qos.service.j2
    dest: /etc/systemd/system/tc-qos.service
  notify: reload systemd

- name: Enable and start QoS service
  systemd:
    name: tc-qos
    enabled: yes
    state: started

- name: Configure network monitoring
  template:
    src: network-monitor.sh.j2
    dest: /usr/local/bin/network-monitor.sh
    mode: '0755'

- name: Configure network monitoring service
  template:
    src: network-monitor.service.j2
    dest: /etc/systemd/system/network-monitor.service
  notify: reload systemd

- name: Enable and start network monitoring
  systemd:
    name: network-monitor
    enabled: yes
    state: started

- name: Configure network metrics exporter
  template:
    src: network-metrics.yml.j2
    dest: /etc/prometheus/targets/network.yml
  notify: reload prometheus

- name: Install network testing tools
  apt:
    name:
      - iperf3
      - mtr
      - traceroute
      - nmap
      - netcat
    state: present

- name: Configure network testing scripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  with_items:
    - test-network-latency.sh
    - test-network-bandwidth.sh
    - test-network-connectivity.sh

- name: Configure network testing cron jobs
  cron:
    name: "{{ item.name }}"
    job: "/usr/local/bin/{{ item.script }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
  with_items:
    - { name: "Test network latency", script: "test-network-latency.sh", minute: "*/5", hour: "*" }
    - { name: "Test network bandwidth", script: "test-network-bandwidth.sh", minute: "0", hour: "*/6" }
    - { name: "Test network connectivity", script: "test-network-connectivity.sh", minute: "*/15", hour: "*" }
