name: 'Ansible CI'

on:
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ansible/**'

jobs:
  ansible-lint:
    name: 'Ansible Lint'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint yamllint

    - name: Run ansible-lint
      run: |
        ansible-lint ansible/playbooks/*.yml
        ansible-lint ansible/roles/**/tasks/*.yml

    - name: Run yamllint
      run: |
        yamllint ansible/playbooks/
        yamllint ansible/roles/
